### ISSUE TITLE
Example for replacing the OrchardCore.Users  Register action with custom controller action?

### ISSUE THREAD

**Issue by giannik** [EasyOC/EasyOC.Modules#1]
If my understanding is correct we replace the built in Register controller/action with our own controller action so that /Register goes to our own custom implementation ?
Can you give an example for this use case ?
Also what if my own action has some additional parameters to pass in.

**Comment by hyzx86** [comment]
You can get any request information and additional parameters via `IHttpContextAccessor`

**Comment by hyzx86** [comment]
sample see [here](https://github.com/EasyOC/EasyOC.Modules/tree/main/src/EasyOC.ReplaceAction)
